#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: pomelo925/2025-spring-course:robotic-nav-exploration

  volumes:
    # GUI
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix

    # workspace 
    - ../../110033226_HW1:/110033226_HW1

  environment:
    - DISPLAY=${DISPLAY}
  
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s

##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common]
    container_name: robotic-nav-exploration
    command: ["/bin/bash"]