#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: pomelo925/2025-nthu-rne:hw3

  volumes:
    # GUI
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix

    # workspace 
    - ../../110033226_HW3:/110033226_HW3

  environment:
    - DISPLAY=${DISPLAY}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s

##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common]
    container_name: hw3_raw
    command: ["/bin/bash"]